/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.ConexaoDAO;
import DAO.MinhaData;
import DAO.MinhaHora;
import DTO.BatizadosDTO;
import java.awt.Component;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.Image;
import java.awt.Graphics;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author NOTEHOME
 */
public class FrmTelaPrincipal extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaPrincipal
     */
    public FrmTelaPrincipal() {

        conn = ConexaoDAO.conectaDB();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        timer1.start();

//        MinhaData minha = new MinhaData(new Date()); 
//        lbData.setText(minha.getDiaSemana()+",   "+minha.getDataHora());        
    }

    private Component getInstance() {
        return this;
    }

    private void imprimir_relatorio() {

//        int confirma = JOptionPane.showInternalConfirmDialog(getInstance(), "Confirma a emissão do relatório?", "Atenção", JOptionPane.YES_OPTION);
//        if (confirma == JOptionPane.YES_OPTION) {
        try {
            //pst.executeQuery("select * from batizados");
            JasperPrint jpPrint = JasperFillManager.fillReport("D:/ProjectsNetBeans/reports/batizados.jasper", new HashMap(), conn);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
            jv.toFront();

        } catch (Exception erro) {
            JOptionPane.showInternalMessageDialog(rootPane, "Erro ao gerar o relatório!" + erro);
        }
        //}

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        ImageIcon icon = new ImageIcon(getClass().getResource("/ICONS/fundoSSB.jpeg"));
        Image image = icon.getImage();
        desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        lblUsu = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menuCadBatiz = new javax.swing.JMenuItem();
        menuCadCris = new javax.swing.JMenuItem();
        menuCadMatr = new javax.swing.JMenuItem();
        menucadPE = new javax.swing.JMenuItem();
        menuCadUsu = new javax.swing.JMenuItem();
        MenuConsulta = new javax.swing.JMenu();
        menuConsBat2 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelBatiz = new javax.swing.JMenuItem();
        menuRelCris = new javax.swing.JMenuItem();
        menuRelMatr = new javax.swing.JMenuItem();
        menuRelPE = new javax.swing.JMenuItem();
        menuRelUsu = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuAjuSob = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        menuOpcSair = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCP");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(255, 255, 255));
        desktop.setPreferredSize(new java.awt.Dimension(1024, 680));

        lblUsu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsu.setText("Usuário");
        lblUsu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbData.setBackground(new java.awt.Color(204, 204, 204));
        lbData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbData.setText("DtHr");
        lbData.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Usuário:");

        desktop.setLayer(lblUsu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lbData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        Menu.setPreferredSize(new java.awt.Dimension(315, 35));

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/add24x24.png"))); // NOI18N
        menuCadastros.setText("Cadastro");

        menuCadBatiz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        menuCadBatiz.setText("Batizados");
        menuCadBatiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadBatizActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadBatiz);

        menuCadCris.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuCadCris.setText("Crismas");
        menuCadastros.add(menuCadCris);

        menuCadMatr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        menuCadMatr.setText("Matrimônios");
        menuCadastros.add(menuCadMatr);

        menucadPE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menucadPE.setText("Primeira Eucarístia");
        menuCadastros.add(menucadPE);

        menuCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuCadUsu.setText("Usuários");
        menuCadUsu.setEnabled(false);
        menuCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadUsuActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadUsu);

        Menu.add(menuCadastros);

        MenuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/consulta24x24.png"))); // NOI18N
        MenuConsulta.setText("Consulta");

        menuConsBat2.setText("Batizados");
        menuConsBat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsBat2ActionPerformed(evt);
            }
        });
        MenuConsulta.add(menuConsBat2);

        jMenuItem2.setText("Crismas");
        MenuConsulta.add(jMenuItem2);

        jMenuItem3.setText("Matrimônios");
        MenuConsulta.add(jMenuItem3);

        jMenuItem4.setText("Primeira Eucaristia");
        MenuConsulta.add(jMenuItem4);

        Menu.add(MenuConsulta);

        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/report24x24.png"))); // NOI18N
        menuRelatorios.setText("Relatórios");

        menuRelBatiz.setText("Batizados");
        menuRelBatiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelBatizActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelBatiz);

        menuRelCris.setText("Crismas");
        menuRelatorios.add(menuRelCris);

        menuRelMatr.setText("Matrimônios");
        menuRelatorios.add(menuRelMatr);

        menuRelPE.setText("Primeira Eucarítia");
        menuRelatorios.add(menuRelPE);

        menuRelUsu.setText("Usuários");
        menuRelatorios.add(menuRelUsu);

        Menu.add(menuRelatorios);

        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/info24x24.png"))); // NOI18N
        menuAjuda.setText("Ajuda");

        menuAjuSob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        menuAjuSob.setText("Sobre");
        menuAjuSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjuSobActionPerformed(evt);
            }
        });
        menuAjuda.add(menuAjuSob);

        Menu.add(menuAjuda);

        menuOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/settings24x24.png"))); // NOI18N
        menuOpcoes.setText("Opções");

        menuOpcSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuOpcSair.setText("Sair");
        menuOpcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcSairActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuOpcSair);

        Menu.add(menuOpcoes);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1296, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // as linhas abaixo substituem a label data lbldata pela data atual do sistema
        //ao inicilizar o form
//        Date data = new Date();    
//        DateFormat formatador = DateFormat.getDateInstance(DateFormat.FULL);
//       lblData.setText(formatador.format(data));

//        MinhaHora hora = new MinhaHora(new Date()); 
//        lbData.setText(hora.getDataHora());
        //MinhaData minha = new MinhaData(new Date());
        //lbData.setText(minha.getDiaSemana()+", "+minha.getDataHora());

    }//GEN-LAST:event_formWindowActivated

    private void menuOpcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcSairActionPerformed
        // exibe uma caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair do sistema?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuOpcSairActionPerformed

    private void menuAjuSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjuSobActionPerformed
        // chamando a tela sobre
        FrmSobre sobre = new FrmSobre();
        desktop.add(sobre);
        sobre.show();
        //sobre.setVisible(true);
    }//GEN-LAST:event_menuAjuSobActionPerformed

    private void menuCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadUsuActionPerformed
        // as linhas abaixo irao abrir o form TelaUsuario dentro do desktopPane
        FrmTelaUsuario usuario = new FrmTelaUsuario();
        desktop.add(usuario);
        usuario.show();
        //usuario.setVisible(true);

    }//GEN-LAST:event_menuCadUsuActionPerformed

    private void menuCadBatizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadBatizActionPerformed
        FrmTelaBatizado batizados = new FrmTelaBatizado();
        desktop.add(batizados);
        batizados.show();

    }//GEN-LAST:event_menuCadBatizActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime

        MinhaData minha = new MinhaData(new Date());
        lbData.setText(minha.getDiaSemana() + ", " + minha.getDataHora());
    }//GEN-LAST:event_timer1OnTime

    private void menuRelBatizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelBatizActionPerformed
        //imprimir_relatorio();
        int confirma = JOptionPane.showConfirmDialog(null,"Confirma a impressão deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            try {
                JasperPrint print = JasperFillManager.fillReport("D:/ProjectsNetBeans/reports/batizados.jasper",null,conn);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_menuRelBatizActionPerformed

    private void menuConsBat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsBat2ActionPerformed

        FrmConsBatizado consb = new FrmConsBatizado();
        desktop.add(consb);
        consb.show();
        consb.toFront();
    }//GEN-LAST:event_menuConsBat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lbData;
    public static javax.swing.JLabel lblUsu;
    private javax.swing.JMenuItem menuAjuSob;
    private javax.swing.JMenu menuAjuda;
    public static javax.swing.JMenuItem menuCadBatiz;
    private javax.swing.JMenuItem menuCadCris;
    private javax.swing.JMenuItem menuCadMatr;
    public static javax.swing.JMenuItem menuCadUsu;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuConsBat2;
    private javax.swing.JMenuItem menuOpcSair;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenuItem menuRelBatiz;
    private javax.swing.JMenuItem menuRelCris;
    private javax.swing.JMenuItem menuRelMatr;
    private javax.swing.JMenuItem menuRelPE;
    private javax.swing.JMenuItem menuRelUsu;
    public static javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menucadPE;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
